### PR TITLE
 Converted Counters to Gauges for reset functionality 

### PR DESCRIPTION
**Pull request by deepak1725**

### CODE REVIEW

**Comment by deepak1725** [comment]
[test]

**Comment by deepak1725** [comment]
Unit Tests are passing https://ci.centos.org/job/devtools-metrics-accumulator-fabric8-analytics/23/

**Comment by miteshvp** [comment]
@deepak1725 - have you tested this on dev cluster?

**Comment by deepak1725** [comment]
@miteshvp 
ss

**Review by miteshvp — APPROVED** [review]
LGTM.

**Pull request merged**
